# Generated by Django 4.2.5 on 2024-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_description_alter_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('OPERATING EXPENSE', 'operating expense'), ('TRAVEL', 'TRAVEL'), ('RENT', 'RENT'), ('OTHERS', 'OTHERS'), ('FOOD', 'FOOD')], max_length=255),
        ),
    ]
